<#
Windows 11 PowerShell bootstrap

Usage:
  1. Clone dotfiles repo, e.g.
       git clone <your-repo-url> $HOME\dotfiles\.config

  2. From PowerShell 7:
       cd $HOME\dotfiles\.config
       .\bootstrap.ps1

  3. Restart Windows Terminal or run:
       . $PROFILE

Expected repo layout:
  dotfiles\
	.config\
	  bootstrap.ps1
	  powershell\
	    Microsoft.PowerShell_profile.ps1
	  ohmyposh\
	    tiramisu.omp.toml

Notes:
  - This script creates the real PowerShell profile at $PROFILE as a tiny
    bootstrap file that sources the version-controlled profile.
  - Install/select a Nerd Font manually in Windows Terminal if icons look wrong.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$DotfilesRoot = $PSScriptRoot
$RepoProfile = Join-Path $DotfilesRoot "powershell\Microsoft.PowerShell_profile.ps1"
$RepoTheme   = Join-Path $DotfilesRoot "ohmyposh\tiramisu.omp.toml"

function Write-Step($message) {
    Write-Host "`n==> $message" -ForegroundColor Cyan
}

function Install-WingetPackage($id) {
    $existing = winget list --id $id --exact 2>$null
    if ($LASTEXITCODE -eq 0 -and $existing -match [regex]::Escape($id)) {
        Write-Host "Already installed: $id"
        return
    }

    Write-Host "Installing: $id"
    winget install --id $id --exact --source winget
}

Write-Step "Checking expected dotfiles"

if (-not (Test-Path $RepoProfile)) {
    throw "Could not find repo profile: $RepoProfile"
}

if (-not (Test-Path $RepoTheme)) {
    Write-Warning "Could not find Oh My Posh theme: $RepoTheme"
}

Write-Step "Installing winget packages"

Install-WingetPackage "Git.Git"
Install-WingetPackage "JanDeDobbeleer.OhMyPosh"
Install-WingetPackage "ajeetdsouza.zoxide"
Install-WingetPackage "junegunn.fzf"

Write-Step "Installing PowerShell modules"

Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

Install-Module posh-git -Scope CurrentUser -Force -AllowClobber
Install-Module PSFzf    -Scope CurrentUser -Force -AllowClobber

Write-Step "Creating PowerShell profile bootstrap"

$profileDir = Split-Path $PROFILE -Parent
New-Item -ItemType Directory -Path $profileDir -Force | Out-Null

if (Test-Path $PROFILE) {
    $backup = "$PROFILE.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item $PROFILE $backup
    Write-Host "Backed up existing profile to: $backup"
}

@"
# Auto-generated by dotfiles bootstrap.ps1
# Real profile lives in the dotfiles repo.

`$dotfilesProfile = "$RepoProfile"

if (Test-Path `$dotfilesProfile) {
    . `$dotfilesProfile
}
else {
    Write-Warning "Dotfiles profile not found: `$dotfilesProfile"
}
"@ | Set-Content -Path $PROFILE -Encoding UTF8

Write-Step "Done"

Write-Host "Profile points to: $RepoProfile"
Write-Host "Theme expected at:  $RepoTheme"
Write-Host ""
Write-Host "Restart Windows Terminal or run:"
Write-Host "  . `$PROFILE"
